export const HELLO = "WORKER!HELLO";
export const HELLO_SUCCESS = "HELLO_SUCCESS";
export const HELLO_ERROR = "HELLO_ERROR";

export const SOMETHING = "WORKER!SOMETHING";
export const SOMETHING_SUCCESS = "SOMETHING_SUCCESS";
export const SOMETHING_SUCCESS2 = "SOMETHING_SUCCESS2";
export const SOMETHING_ERROR = "SOMETHING_ERROR";

export const CRASH = "WORKER!CRASH";
export const CRASH_SUCCESS = "CRASH_SUCCESS";
export const CRASH_ERROR = "CRASH_ERROR";

export const FORGET = "WORKER!FORGET";
export const FORGET_TMP = "FORGET_TMP";
export const FORGET_SUCCESS = "FORGET_SUCCESS";
export const FORGET_ERROR = "FORGET_ERROR";